Document: simulator
Title: Debian simulator Manual
Author: <insert document author here>
Abstract: This manual describes what simulator is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/simulator/simulator.sgml.gz

Format: postscript
Files: /usr/share/doc/simulator/simulator.ps.gz

Format: text
Files: /usr/share/doc/simulator/simulator.text.gz

Format: HTML
Index: /usr/share/doc/simulator/html/index.html
Files: /usr/share/doc/simulator/html/*.html
