Document: usfsim
Title: Debian usfsim Manual
Author: <insert document author here>
Abstract: This manual describes what usfsim is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/usfsim/usfsim.sgml.gz

Format: postscript
Files: /usr/share/doc/usfsim/usfsim.ps.gz

Format: text
Files: /usr/share/doc/usfsim/usfsim.text.gz

Format: HTML
Index: /usr/share/doc/usfsim/html/index.html
Files: /usr/share/doc/usfsim/html/*.html
